from __future__ import annotations

from api.operator_console_execution_review import CONSOLE_HTML_V32

FINAL_PREVIEW_SCRIPT = r"""
<style>
.final-preview{margin-top:14px;background:#fff;border:1px solid #dce9f8;border-radius:18px;padding:18px;box-shadow:0 12px 34px rgba(11,47,97,.05)}.final-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.final-cell{border:1px solid #e2edf8;border-radius:12px;padding:12px;background:#fbfdff}.final-cell small{display:block;color:#63758d}.final-cell strong{display:block;margin-top:4px}.final-warn{padding:12px;border:1px solid #f2dfb8;background:#fff8ea;border-radius:10px;color:#7c4b00;margin-bottom:10px}.final-ok{padding:12px;border:1px solid #cfe7d8;background:#f2fbf5;border-radius:10px;color:#147a46;margin-bottom:10px}
</style>
<script>
async function loadFinalAuthorizationPreview(recordId){const view=document.getElementById('view');if(!view||!recordId)return;let box=document.getElementById('final-auth-preview');if(!box){box=document.createElement('section');box.id='final-auth-preview';box.className='final-preview';const timeline=view.querySelector('.timeline');if(timeline)view.insertBefore(box,timeline);else view.appendChild(box)}box.innerHTML='<h3>Final Read-Only Authorization Preview</h3><div class="muted">Checking newest execution-review manifest…</div>';try{const r=await fetch('/operator/api/cases/'+encodeURIComponent(recordId)+'/execution-authorization-context',{credentials:'same-origin'});if(r.status===401){location.href='/operator/login';return}if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.detail||'preview unavailable')}const d=await r.json();if(!d.ready){box.innerHTML=`<h3>Final Read-Only Authorization Preview</h3><div class="final-warn">Not ready: ${esc((d.reason||'not ready').replaceAll('_',' '))}</div>`;return}const p=d.proposed_execution;const prior=d.latest_execution_authorization?`Latest final disposition: ${esc(d.latest_execution_authorization.decision)} · ${esc(d.latest_execution_authorization.state)}${d.latest_execution_authorization.expired===true?' · expired':''}`:'No final execution authorization has been recorded for this manifest.';box.innerHTML=`<h3>Final Read-Only Authorization Preview</h3><div class="final-ok">This manifest is current and eligible for a <strong>separate final human authorization</strong>. No authorize button is exposed in this version.</div><div class="final-grid"><div class="final-cell"><small>Capability</small><strong>${esc(p.capability_id)}</strong></div><div class="final-cell"><small>Contract</small><strong>${esc(p.contract_id)}</strong></div><div class="final-cell"><small>Effect class</small><strong>${esc(p.effect_class)}</strong></div><div class="final-cell"><small>TTL</small><strong>${esc(d.ttl_minutes.default)} min default</strong></div></div><div class="final-cell" style="margin-top:10px"><small>Allowlisted operations</small><strong>${esc((p.operations||[]).join(', '))}</strong></div><div class="final-warn" style="margin-top:10px">Required before final authorization: scope confirmation, effects confirmation, live capability-health confirmation, and rationale. Even final authorization will not dispatch automatically.</div><div class="muted">${prior}</div>`}catch(err){box.innerHTML=`<h3>Final Read-Only Authorization Preview</h3><div class="muted">${esc(err.message||'Preview unavailable.')}</div>`}}
const _v32LoadCase=loadCase;loadCase=async function(id){await _v32LoadCase(id);await loadFinalAuthorizationPreview(id)};setTimeout(()=>{if(selected)loadFinalAuthorizationPreview(selected)},1300);
</script>
"""

CONSOLE_HTML_V33 = CONSOLE_HTML_V32.replace("</body>", FINAL_PREVIEW_SCRIPT + "</body>")
