from __future__ import annotations

from api.operator_console_final_authorization import CONSOLE_HTML_V34

DISPATCH_PREVIEW_SCRIPT = r"""
<style>
.dispatch-preview{margin-top:14px;background:#fff;border:1px solid #dce9f8;border-radius:18px;padding:18px;box-shadow:0 12px 34px rgba(11,47,97,.05)}.dispatch-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px}.dispatch-cell{border:1px solid #e2edf8;border-radius:12px;padding:12px;background:#fbfdff}.dispatch-cell small{display:block;color:#63758d}.dispatch-cell strong{display:block;margin-top:4px}.dispatch-warn{padding:12px;border:1px solid #f2dfb8;background:#fff8ea;border-radius:10px;color:#7c4b00}.dispatch-ok{padding:12px;border:1px solid #cfe7d8;background:#f2fbf5;border-radius:10px;color:#147a46}
</style>
<script>
async function loadDispatchPreview(recordId){const view=document.getElementById('view');if(!view||!recordId)return;let box=document.getElementById('dispatch-preview');if(!box){box=document.createElement('section');box.id='dispatch-preview';box.className='dispatch-preview';const timeline=view.querySelector('.timeline');if(timeline)view.insertBefore(box,timeline);else view.appendChild(box)}box.innerHTML='<h3>Dispatch Preview</h3><div class="muted">Checking newest final authorization and runner contract…</div>';try{const r=await fetch('/operator/api/cases/'+encodeURIComponent(recordId)+'/dispatch-context',{credentials:'same-origin'});if(r.status===401){location.href='/operator/login';return}if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.detail||'dispatch preview unavailable')}const d=await r.json();if(!d.ready){box.innerHTML=`<h3>Dispatch Preview</h3><div class="dispatch-warn">Not ready: ${esc((d.reason||'not ready').replaceAll('_',' '))}</div>`;return}const c=d.dispatch_contract;box.innerHTML=`<h3>Dispatch Preview</h3><div class="dispatch-ok">A current short-lived read-only authorization exists. This preview does not create a ticket or run anything.</div><div class="dispatch-grid"><div class="dispatch-cell"><small>Capability</small><strong>${esc(c.capability_id)}</strong></div><div class="dispatch-cell"><small>Contract</small><strong>${esc(c.contract_id)}</strong></div><div class="dispatch-cell"><small>Effect</small><strong>${esc(c.effect_class)}</strong></div><div class="dispatch-cell"><small>Authorization remaining</small><strong>${esc(d.authorization_remaining_seconds)} sec</strong></div></div><div class="dispatch-cell" style="margin-top:10px"><small>Runner allowlist</small><strong>${esc((c.allowed_operations||[]).join(', '))}</strong></div><p class="muted">Tickets are single-use, live for ${esc(d.ticket.ttl_minutes.min)}–${esc(d.ticket.ttl_minutes.max)} minutes, and can never outlive the authorization. Next gate: ${esc(d.next_gate)}</p>`}catch(err){box.innerHTML=`<h3>Dispatch Preview</h3><div class="muted">${esc(err.message||'Preview unavailable.')}</div>`}}
const _v34LoadCase=loadCase;loadCase=async function(id){await _v34LoadCase(id);await loadDispatchPreview(id)};setTimeout(()=>{if(selected)loadDispatchPreview(selected)},1500);
</script>
"""

CONSOLE_HTML_V35 = CONSOLE_HTML_V34.replace("</body>", DISPATCH_PREVIEW_SCRIPT + "</body>")
