from __future__ import annotations

from api.operator_console_authorization import CONSOLE_HTML_V29

PREVIEW_SCRIPT = r"""
<style>
.exec-preview{margin-top:14px;background:#fff;border:1px solid #dce9f8;border-radius:18px;padding:18px;box-shadow:0 12px 34px rgba(11,47,97,.05)}.contract-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px;margin-top:10px}.contract-cell{border:1px solid #e2edf8;border-radius:12px;padding:12px;background:#fbfdff}.contract-cell small{display:block;color:#63758d}.contract-cell strong{display:block;margin-top:4px}.not-ready{padding:12px;border:1px solid #f2dfb8;background:#fff8ea;border-radius:10px;color:#7c4b00}.ready-note{padding:12px;border:1px solid #cfe7d8;background:#f2fbf5;border-radius:10px;color:#147a46}
</style>
<script>
async function loadExecutionReviewPreview(recordId){const view=document.getElementById('view');if(!view||!recordId)return;let box=document.getElementById('execution-review-preview');if(!box){box=document.createElement('section');box.id='execution-review-preview';box.className='exec-preview';const timeline=view.querySelector('.timeline');if(timeline)view.insertBefore(box,timeline);else view.appendChild(box)}box.innerHTML='<h3>Execution Review Preview</h3><div class="muted">Resolving current human authorization and capability contract…</div>';try{const r=await fetch('/operator/api/cases/'+encodeURIComponent(recordId)+'/execution-review-context',{credentials:'same-origin'});if(r.status===401){location.href='/operator/login';return}if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.detail||'preview unavailable')}const d=await r.json();if(!d.ready){let detail=d.reason||'not ready';if(d.reason==='target_capability_contract_not_allowlisted'&&d.allowlisted_targets)detail+=`. Allowlisted targets: ${d.allowlisted_targets.join(', ')}`;box.innerHTML=`<h3>Execution Review Preview</h3><div class="not-ready">Not ready: ${esc(detail.replaceAll('_',' '))}</div><p class="muted">No execution-review manifest is created by this preview.</p>`;return}const c=d.proposed_contract;const ops=(c.operations||[]).map(x=>esc(x)).join(', ');box.innerHTML=`<h3>Execution Review Preview</h3><div class="ready-note">Human approval for <strong>execution review only</strong> is current. This preview still creates no manifest and grants no execution or dispatch authority.</div><div class="contract-grid"><div class="contract-cell"><small>Capability</small><strong>${esc(c.capability_id)}</strong></div><div class="contract-cell"><small>Contract</small><strong>${esc(c.contract_id)}</strong></div><div class="contract-cell"><small>Effect class</small><strong>${esc(c.effect_class)}</strong></div><div class="contract-cell"><small>Transport</small><strong>${esc(c.transport)}</strong></div></div><div class="contract-cell" style="margin-top:10px"><small>Allowlisted operations</small><strong>${ops}</strong></div><p class="muted">Next gate: ${esc(d.next_gate)}</p>`}catch(err){box.innerHTML=`<h3>Execution Review Preview</h3><div class="muted">${esc(err.message||'Preview unavailable.')}</div>`}}
const _v29LoadCase=loadCase;loadCase=async function(id){await _v29LoadCase(id);await loadExecutionReviewPreview(id)};setTimeout(()=>{if(selected)loadExecutionReviewPreview(selected)},1100);
</script>
"""

CONSOLE_HTML_V30 = CONSOLE_HTML_V29.replace("</body>", PREVIEW_SCRIPT + "</body>")
