from __future__ import annotations

from api.operator_console_stage import CONSOLE_HTML_V43

ATTENTION_SCRIPT = r"""
<style>
.attn-panel{margin:0 0 18px;background:#fff;border:1px solid #dce9f8;border-radius:18px;padding:18px;box-shadow:0 12px 34px rgba(11,47,97,.05)}.attn-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:12px}.attn-summary{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:12px}.attn-pill{border:1px solid #dce9f8;border-radius:999px;padding:7px 10px;font-size:12px;background:#f8fbff}.attn-list{display:grid;gap:8px}.attn-row{display:grid;grid-template-columns:minmax(170px,1.2fr) minmax(140px,.8fr) auto;gap:12px;align-items:center;border:1px solid #e2edf8;border-radius:12px;padding:11px 12px;background:#fbfdff;cursor:pointer}.attn-row:hover{border-color:#9fc4f5}.attn-title{font-weight:800}.attn-meta{font-size:12px;color:#63758d}.attn-status{font-size:11px;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.attn-status.needs_human_action{color:#1769e0}.attn-status.blocked{color:#b42318}.attn-status.ready_for_operator{color:#8a5a00}.attn-status.cycle_complete{color:#147a46}.attn-status.waiting{color:#63758d}@media(max-width:760px){.attn-row{grid-template-columns:1fr}.attn-status{text-align:left}}
</style>
<script>
async function loadAttentionQueue(){const view=document.getElementById('view');if(!view)return;let box=document.getElementById('attention-queue-panel');if(!box){box=document.createElement('section');box.id='attention-queue-panel';box.className='attn-panel';view.prepend(box)}box.innerHTML='<h3>Case Attention Queue</h3><div class="muted">Resolving current governed stages…</div>';try{const r=await fetch('/operator/api/attention-queue',{credentials:'same-origin'});if(r.status===401){location.href='/operator/login';return}if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.detail||'queue unavailable')}const d=await r.json();const c=d.counts||{};const pills=[['needs_human_action','human action'],['blocked','blocked'],['ready_for_operator','ready'],['waiting','waiting'],['cycle_complete','complete']].map(([k,l])=>`<span class="attn-pill"><strong>${Number(c[k]||0)}</strong> ${l}</span>`).join('');const rows=(d.items||[]).map(x=>`<div class="attn-row" data-record="${esc(x.current_record_id)}"><div><div class="attn-title">${esc(x.intent_label||'VMI Review')}</div><div class="attn-meta">Generation ${Number(x.generation||0)+1} · ${esc(x.query_preview||'')}</div></div><div><strong>${esc(x.current_stage_label|| (x.cycle_complete?'Cycle complete':'No current gate'))}</strong>${x.blocking_reason?`<div class="attn-meta">${esc(String(x.blocking_reason).replaceAll('_',' '))}</div>`:''}</div><div class="attn-status ${esc(x.status)}">${esc(String(x.status||'').replaceAll('_',' '))}</div></div>`).join('')||'<div class="muted">No governed cases.</div>';box.innerHTML=`<div class="attn-head"><div><h3 style="margin:0">Case Attention Queue</h3><div class="muted">Operational ordering only · no decision priority inferred</div></div><span class="tag">${Number(d.total||0)} cases</span></div><div class="attn-summary">${pills}</div><div class="attn-list">${rows}</div>`;box.querySelectorAll('.attn-row').forEach(row=>row.addEventListener('click',()=>{const id=row.dataset.record;if(id){selected=id;document.querySelectorAll('.case').forEach(x=>x.classList.toggle('active',x.dataset.id===id));loadCase(id)}}))}catch(err){box.innerHTML=`<h3>Case Attention Queue</h3><div class="muted">${esc(err.message||'Queue unavailable.')}</div>`}}
const _v43LoadCases=loadCases;loadCases=async function(){await _v43LoadCases();await loadAttentionQueue()};setTimeout(loadAttentionQueue,420);
</script>
"""

CONSOLE_HTML_V44 = CONSOLE_HTML_V43.replace("</body>", ATTENTION_SCRIPT + "</body>")
