from __future__ import annotations

from api.operator_console_evidence_return import CONSOLE_HTML_V40

REFRESH_SCRIPT = r"""
<style>
.refresh-panel{margin-top:14px;background:#fff;border:1px solid #dce9f8;border-radius:18px;padding:18px;box-shadow:0 12px 34px rgba(11,47,97,.05)}.refresh-note{padding:12px;border:1px solid #cfe7d8;background:#f2fbf5;border-radius:10px;color:#147a46;margin-bottom:10px}.refresh-warn{padding:12px;border:1px solid #f2dfb8;background:#fff8ea;border-radius:10px;color:#7c4b00;margin-bottom:10px}.refresh-confirm{display:flex;gap:9px;align-items:flex-start;padding:12px;border:1px solid #e2edf8;background:#fbfdff;border-radius:10px}.refresh-panel button{width:100%;margin-top:10px;border:0;border-radius:10px;padding:12px;background:#1769e0;color:#fff;font-weight:900;cursor:pointer}.refresh-panel button:disabled{opacity:.5;cursor:not-allowed}.refresh-status{min-height:20px;margin-top:10px;font-size:13px}.refresh-status.ok{color:#147a46}.refresh-status.err{color:#b42318}
</style>
<script>
async function loadDecisionRefreshControl(recordId){const view=document.getElementById('view');if(!view||!recordId)return;let box=document.getElementById('decision-refresh-control');if(!box){box=document.createElement('section');box.id='decision-refresh-control';box.className='refresh-panel';const timeline=view.querySelector('.timeline');if(timeline)view.insertBefore(box,timeline);else view.appendChild(box)}box.innerHTML='<h3>Refresh Decision Context</h3><div class="muted">Checking returned evidence…</div>';try{const r=await fetch('/operator/api/cases/'+encodeURIComponent(recordId)+'/decision-refresh-context',{credentials:'same-origin'});if(r.status===401){location.href='/operator/login';return}if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.detail||'decision refresh context unavailable')}const d=await r.json();if(!d.ready){box.innerHTML=`<h3>Refresh Decision Context</h3><div class="muted">Not available: ${esc((d.reason||'not ready').replaceAll('_',' '))}</div>`;return}const e=d.evidence_return;box.innerHTML=`<h3>Refresh Decision Context</h3><div class="refresh-note">Evidence return ${esc(e.evidence_return_id)} is ready to be combined with the prior decision context.</div><div class="refresh-warn">A refresh creates a new human-review snapshot only. It does not resolve prior gaps automatically, approve anything, dispatch, execute, or create a successor review cycle.</div><label class="refresh-confirm"><input type="checkbox" id="refresh-confirm"><span>I want to create one refreshed decision snapshot from this returned evidence for human review.</span></label><button id="refresh-button">Create decision refresh</button><div id="refresh-status" class="refresh-status"></div>`;box.querySelector('#refresh-button').onclick=async()=>{const status=box.querySelector('#refresh-status');const btn=box.querySelector('#refresh-button');status.textContent='';status.className='refresh-status';if(!box.querySelector('#refresh-confirm').checked){status.textContent='Explicit decision-refresh confirmation is required.';status.className='refresh-status err';return}btn.disabled=true;try{const csrf=await loadConsoleCsrf();const rr=await fetch('/operator/api/evidence-returns/'+encodeURIComponent(e.evidence_return_id)+'/decision-refresh',{method:'POST',headers:{'content-type':'application/json','x-vmi-csrf':csrf},credentials:'same-origin',body:JSON.stringify({confirm_decision_refresh:true})});if(!rr.ok){const x=await rr.json().catch(()=>({}));throw new Error(x.detail||'Decision refresh rejected')}const x=await rr.json();status.textContent=`Decision refresh ${x.packet.refresh_id} recorded. Successor review created automatically: false.`;status.className='refresh-status ok';setTimeout(()=>loadCase(recordId),350)}catch(err){status.textContent=String(err.message||err);status.className='refresh-status err'}finally{btn.disabled=false}}}catch(err){box.innerHTML=`<h3>Refresh Decision Context</h3><div class="muted">${esc(err.message||'Unavailable.')}</div>`}}
const _v40LoadCase=loadCase;loadCase=async function(id){await _v40LoadCase(id);await loadDecisionRefreshControl(id)};setTimeout(()=>{if(selected)loadDecisionRefreshControl(selected)},2000);
</script>
"""

CONSOLE_HTML_V41 = CONSOLE_HTML_V40.replace("</body>", REFRESH_SCRIPT + "</body>")
