from __future__ import annotations

from api.operator_console_execution_preview import CONSOLE_HTML_V30

EXEC_REVIEW_SCRIPT = r"""
<style>
.exec-prepare{margin-top:14px;background:#fff;border:1px solid #dce9f8;border-radius:18px;padding:18px;box-shadow:0 12px 34px rgba(11,47,97,.05)}.exec-prepare textarea{width:100%;border:1px solid #cbdced;border-radius:10px;padding:10px;font:inherit;min-height:82px;resize:vertical}.exec-prepare button{margin-top:10px;width:100%;border:0;border-radius:10px;padding:12px;background:#0b2f61;color:#fff;font-weight:800;cursor:pointer}.exec-prepare button:disabled{opacity:.55;cursor:not-allowed}.manifest-status{min-height:20px;margin-top:10px;font-size:13px}.manifest-status.ok{color:#147a46}.manifest-status.err{color:#b42318}.manifest-warning{padding:12px;border:1px solid #f2dfb8;background:#fff8ea;border-radius:10px;color:#7c4b00;margin-bottom:10px}
</style>
<script>
async function loadExecutionReviewPreparation(recordId){const view=document.getElementById('view');if(!view||!recordId)return;let box=document.getElementById('execution-review-prepare');if(!box){box=document.createElement('section');box.id='execution-review-prepare';box.className='exec-prepare';const timeline=view.querySelector('.timeline');if(timeline)view.insertBefore(box,timeline);else view.appendChild(box)}box.innerHTML='<h3>Prepare Execution Review Manifest</h3><div class="muted">Checking whether the current packet is approved for execution review…</div>';try{const r=await fetch('/operator/api/cases/'+encodeURIComponent(recordId)+'/execution-review-context',{credentials:'same-origin'});if(r.status===401){location.href='/operator/login';return}if(!r.ok){const x=await r.json().catch(()=>({}));throw new Error(x.detail||'context unavailable')}const d=await r.json();if(!d.ready){box.innerHTML=`<h3>Prepare Execution Review Manifest</h3><div class="muted">Not available: ${esc((d.reason||'not ready').replaceAll('_',' '))}</div>`;return}const c=d.proposed_contract;box.innerHTML=`<h3>Prepare Execution Review Manifest</h3><div class="manifest-warning">This freezes the reviewed contract into an append-only manifest. It does <strong>not</strong> authorize execution or dispatch. A separate final execution authorization is still required.</div><div class="auth-box"><b>Capability:</b> ${esc(c.capability_id)}<br><b>Contract:</b> ${esc(c.contract_id)}<br><b>Effect:</b> ${esc(c.effect_class)}<br><b>Operations:</b> ${esc((c.operations||[]).join(', '))}</div><textarea id="manifest-purpose" placeholder="Purpose for this execution review manifest"></textarea><button id="manifest-submit">Prepare execution review manifest</button><div id="manifest-status" class="manifest-status"></div>`;box.querySelector('#manifest-submit').onclick=async()=>{const status=box.querySelector('#manifest-status');const btn=box.querySelector('#manifest-submit');status.textContent='';status.className='manifest-status';btn.disabled=true;try{const csrf=await loadConsoleCsrf();const body={reviewer_label:'operator-console',purpose:box.querySelector('#manifest-purpose').value};const rr=await fetch('/operator/api/authorizations/'+encodeURIComponent(d.authorization_id)+'/execution-review',{method:'POST',headers:{'content-type':'application/json','x-vmi-csrf':csrf},credentials:'same-origin',body:JSON.stringify(body)});if(!rr.ok){const x=await rr.json().catch(()=>({}));throw new Error(x.detail||'Manifest preparation rejected')}const x=await rr.json();status.textContent=`Manifest ${x.manifest.manifest_id} prepared. Execution permitted: false. Dispatch permitted: false.`;status.className='manifest-status ok';setTimeout(()=>loadCase(recordId),300)}catch(err){status.textContent=String(err.message||err);status.className='manifest-status err'}finally{btn.disabled=false}}}catch(err){box.innerHTML=`<h3>Prepare Execution Review Manifest</h3><div class="muted">${esc(err.message||'Unavailable.')}</div>`}}
const _v30LoadCase=loadCase;loadCase=async function(id){await _v30LoadCase(id);await loadExecutionReviewPreparation(id)};setTimeout(()=>{if(selected)loadExecutionReviewPreparation(selected)},1200);
</script>
"""

CONSOLE_HTML_V32 = CONSOLE_HTML_V30.replace("</body>", EXEC_REVIEW_SCRIPT + "</body>")
